# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u5gcoKUJkZxBppEKukFHnSJMxRZERfK4
"""
import os
os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"
import gradio as gr
import numpy as np
import cv2
import tensorflow as tf
from tensorflow.keras.models import load_model

model = load_model("marine_model.h5")

def predict(image):
    img = cv2.resize(image, (224,224))
    img = img / 255.0
    img = np.expand_dims(img, axis=0)

    pred = model.predict(img)[0][0]

    if pred > 0.5:
        return "Waste"
    else:
        return "Clean"

interface = gr.Interface(
    fn=predict,
    inputs=gr.Image(type="numpy"),
    outputs="text",
    title="Marine Plastic Detection"
)

interface.launch(server_name="0.0.0.0", server_port=10000)

